# Console and diagnostics
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_LOG=y
CONFIG_LOG_PRINTK=n
CONFIG_LOG_BACKEND_UART=y
# CONFIG_LOG_DEFAULT_LEVEL. 3:INFO

CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=4096

# i.MX Messaging Unit
CONFIG_IPM=y
CONFIG_IPM_LOG_LEVEL_INF=y
CONFIG_IPM_IMX_MAX_DATA_SIZE_16=n
CONFIG_IPM_IMX_MAX_DATA_SIZE_4=y

# Linux remoteproc-compatible OpenAMP firmware
CONFIG_OPENAMP=y
# CONFIG_OPENAMP_MASTER: Explicitly describe the M7 as the remote side
CONFIG_OPENAMP_MASTER=n
# CONFIG_OPENAMP_SLAVE: Explicitly describe the M7 as the remote side
CONFIG_OPENAMP_SLAVE=y
# CONFIG_OPENAMP_WITH_DCACHE: Add the i.MX8MP cache setting from Zephyr’s reference configuration
CONFIG_CACHE_MANAGEMENT=y
CONFIG_OPENAMP_WITH_DCACHE=y

CONFIG_OPENAMP_RSC_TABLE=y
CONFIG_OPENAMP_RSC_TABLE_NUM_RPMSG_BUFF=8
CONFIG_OPENAMP_RSC_TABLE_IPM_RX_ID=1
CONFIG_OPENAMP_RSC_TABLE_IPM_TX_ID=0

CONFIG_KERNEL_BIN_NAME="rpmsg_lite_sample"
