# from prj.conf (Nucleo board)
CONFIG_GPIO=y
CONFIG_ADC=n
CONFIG_DAC=n
CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL. 3:INFO
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_ZERO_LATENCY_IRQS=y
CONFIG_LOG_MODE_IMMEDIATE=y

# iMX definitions
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_INPUT=y
CONFIG_FPU=y

# RPMsg service sample integration
# If you want raw, independent UART marker behavior, disable
# printk-to-log redirection (set CONFIG_LOG_PRINTK=n) and keep CONFIG_PRINTK=y.
CONFIG_LOG_PRINTK=n
CONFIG_PRINTK=y
CONFIG_IPM=y
CONFIG_IPM_LOG_LEVEL_INF=y
CONFIG_IPM_IMX_MAX_DATA_SIZE_16=n
CONFIG_IPM_IMX_MAX_DATA_SIZE_4=y
CONFIG_TIMESLICE_SIZE=1
# CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=1024

# OpenAMP
# https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/ipc/openamp_rsc_table/README.rst
# CONFIG_OPENAMP_MASTER=n
# CONFIG_OPENAMP_SLAVE=y
# CONFIG_OPENAMP_VENDOR_ADDR_TRANSLATION=n
# CONFIG_OPENAMP_VRING_ALIGNMENT=4
# CONFIG_OPENAMP=y

# Add Linux remoteproc-compatible .resource_table to the firmware ELF.
# CONFIG_OPENAMP_RSC_TABLE_IPM_RX_ID=1
# CONFIG_OPENAMP_RSC_TABLE_IPM_TX_ID=0
# CONFIG_OPENAMP_RSC_TABLE_NUM_RPMSG_BUFF=8
# CONFIG_OPENAMP_RSC_TABLE=y


# RPMSG_SERVICE
# CONFIG_RPMSG_SERVICE_LOG_LEVEL_DBG=y
# CONFIG_RPMSG_SERVICE_MODE_REMOTE=y
# CONFIG_RPMSG_SERVICE=y

# https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/ipc/openamp_rsc_table/prj.conf
# CONFIG_KERNEL_BIN_NAME="zephyr_openamp_rsc_table"
CONFIG_KERNEL_BIN_NAME="zephyr"
# CONFIG_PRINTK=n
CONFIG_IPM=y
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_HEAP_MEM_POOL_SIZE=1024
CONFIG_OPENAMP=y
CONFIG_OPENAMP_RSC_TABLE_NUM_RPMSG_BUFF=8
CONFIG_OPENAMP_RSC_TABLE=y
CONFIG_OPENAMP_MASTER=n

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_RPMSG=y

# https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/ipc/openamp_rsc_table/boards/imx8mp_evk_mimx8ml8_m7.conf
CONFIG_IPM_IMX_MAX_DATA_SIZE_16=n
CONFIG_IPM_IMX_MAX_DATA_SIZE_4=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_OPENAMP_RSC_TABLE_IPM_RX_ID=1
CONFIG_OPENAMP_RSC_TABLE_IPM_TX_ID=0

# On UART: uart:~$
# CONFIG_SHELL=y
# CONFIG_SHELL_BACKEND_RPMSG=y

# Old
# CONFIG_RPMSG_SERVICE=y
# CONFIG_RPMSG_SERVICE_MODE_REMOTE=y
# CONFIG_RPMSG_SERVICE_LOG_LEVEL_DBG=y
# 
# # Disable resource table path to avoid vring macro redefinition warnings in
# # rpmsg_backend.c when building this app configuration.
# CONFIG_OPENAMP_RSC_TABLE=n
